import { createFileRoute, useRouter } from "@tanstack/react-router";
import { useState } from "react";
import {
  Body,
  BtnOutline,
  BtnPrimary,
  Card,
  CONSEQUENCE,
  HintCard,
  Phone,
  Pill,
  Row,
  ScreenHeader,
  Tile,
} from "@/components/field";
import { Guard } from "@/components/auth-gate";
import { Can, DeniedNote } from "@/components/permissions";
import { useField } from "@/lib/store";
import { downloadText, fmtTime } from "@/lib/utils";
import { toast } from "sonner";

export const Route = createFileRoute("/reports")({
  component: () => (
    <Guard area="reports">
      <ReportsPage />
    </Guard>
  ),
});

/**
 * A02 UC04 reports (R-07) — phone-framed manager/researcher snapshot UI.
 * Not Figure 18 (that is community conflict); this is the conservation report
 * improvement from the group critique.
 */
function ReportsPage() {
  const router = useRouter();
  const { snapshot, generateReport, incidents } = useField();
  const [from, setFrom] = useState("2026-08-01");
  const [to, setTo] = useState("2026-08-31");
  const pendingExcluded = incidents.filter(
    (i) => i.syncState === "PENDING" || i.photoSyncState === "PENDING",
  ).length;

  const emptyWindow =
    snapshot !== null &&
    snapshot.incidentCount === 0 &&
    snapshot.patrolCount === 0;

  function exportCsv() {
    if (!snapshot) return;
    const rows = [
      "field,value",
      `reportId,${snapshot.reportId}`,
      `park,${snapshot.park}`,
      `from,${snapshot.from}`,
      `to,${snapshot.to}`,
      `cutoff,${snapshot.cutoff}`,
      `incidents,${snapshot.incidentCount}`,
      `patrols,${snapshot.patrolCount}`,
      `coverage,${snapshot.coveragePercent}`,
      `conflicts,${snapshot.conflictCount}`,
    ];
    downloadText(`trailguard-${snapshot.reportId.slice(0, 8)}.csv`, rows.join("\n"));
    toast.success("Exported same snapshot");
  }

  return (
    <Phone>
      <ScreenHeader title="Conservation Reports" onBack="home" />
      <Body>
        <div>
          <h2 className="text-[18px] font-bold tracking-tight">Park snapshot</h2>
          <p className="text-[12.5px] text-muted">
            SYNCED records only · coverage = track km ÷ route km · window ≤ 92 days.
          </p>
        </div>

        <Can
          perm="report:generate"
          fallback={
            <DeniedNote>
              Reports are generated by the Park Manager or a Researcher.
            </DeniedNote>
          }
        >
          <Card className="flex flex-col gap-3">
            <label className="block text-[12px] font-semibold text-muted">
              From
              <input
                type="date"
                value={from}
                onChange={(e) => setFrom(e.target.value)}
                className="mt-1 h-11 w-full rounded-xl border border-border bg-surface px-3 text-[14px] text-fg"
              />
            </label>
            <label className="block text-[12px] font-semibold text-muted">
              To
              <input
                type="date"
                value={to}
                onChange={(e) => setTo(e.target.value)}
                className="mt-1 h-11 w-full rounded-xl border border-border bg-surface px-3 text-[14px] text-fg"
              />
            </label>
            <p className="text-[11.5px] text-subtle">
              Yala National Park · pending excluded: {pendingExcluded}
            </p>
            <BtnPrimary
              onClick={() => {
                try {
                  generateReport(from, to);
                  toast.message("Snapshot generated");
                } catch (err) {
                  toast.error(err instanceof Error ? err.message : "Could not generate report");
                }
              }}
            >
              Generate report
            </BtnPrimary>
          </Card>
        </Can>

        {snapshot ? (
          <>
            <div className="flex gap-2">
              <Tile k="Incidents" v={snapshot.incidentCount} />
              <Tile k="Patrols" v={snapshot.patrolCount} />
            </div>
            <div className="flex gap-2">
              <Tile k="Coverage" v={`${snapshot.coveragePercent}%`} />
              <Tile k="Conflicts" v={snapshot.conflictCount} />
            </div>
            {emptyWindow ? (
              <HintCard>
                {CONSEQUENCE.emptyReport} Cutoff {fmtTime(snapshot.cutoff)} is still recorded
                (S5/R-07).
              </HintCard>
            ) : (
              <Card>
                <p className="mb-2 text-[12px] font-semibold text-muted">By type</p>
                {Object.keys(snapshot.byType).length === 0 ? (
                  <p className="text-[13px] text-muted">No synced incidents in this window.</p>
                ) : (
                  Object.entries(snapshot.byType).map(([name, count]) => (
                    <Row key={name} k={name} v={String(count)} strong />
                  ))
                )}
              </Card>
            )}
            <Card>
              <Row k="Snapshot" v={snapshot.reportId.slice(0, 12)} strong />
              <Row k="Cutoff" v={fmtTime(snapshot.cutoff)} strong />
              <div className="mt-1">
                <Pill tone="ok">Immutable</Pill>
              </div>
            </Card>
            <Can
              perm="report:export"
              fallback={<DeniedNote>Export is restricted to Manager and Researcher.</DeniedNote>}
            >
              <BtnOutline onClick={exportCsv}>Export CSV (same snapshot id)</BtnOutline>
            </Can>
          </>
        ) : (
          <HintCard>Choose a window and generate a snapshot over SYNCED field records.</HintCard>
        )}

        <div className="mt-auto pt-2">
          <BtnOutline onClick={() => router.navigate({ to: "/" })}>Back to Ops Desk</BtnOutline>
        </div>
      </Body>
    </Phone>
  );
}
