#!/usr/bin/env bash
# Build a real installable TrailGuard debug APK (DEX + native libs via Gradle).
# Requires: Android SDK, JDK 17 (preferred for RN 0.74 / AGP).
#
# Output:
#   build/apk/trailguard-debug.apk
set -euo pipefail

MOBILE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$MOBILE_DIR"

export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-$HOME/Library/Android/sdk}}"
export ANDROID_HOME="$ANDROID_SDK_ROOT"

# Prefer JDK 17 for React Native / Android Gradle Plugin.
if [[ -z "${JAVA_HOME:-}" ]] || ! "$JAVA_HOME/bin/java" -version 2>&1 | grep -qE '"1[7-9]\.|\"2[0-1]\.'; then
  if [[ -d "/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home" ]]; then
    export JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home"
  elif [[ -d "/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home" ]]; then
    export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"
  elif [[ -d "/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home" ]]; then
    export JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home"
  elif command -v /usr/libexec/java_home >/dev/null 2>&1; then
    export JAVA_HOME="$(/usr/libexec/java_home -v 17 2>/dev/null || /usr/libexec/java_home -v 21 2>/dev/null || true)"
  fi
fi

if [[ -n "${JAVA_HOME:-}" ]] && "$JAVA_HOME/bin/java" -version 2>&1 | grep -qE '"2[5-9]\.|"26\.'; then
  echo "ERROR: JDK 25+ breaks the React Native Gradle plugin. Install JDK 17 or 21 (e.g. temurin-21)."
  exit 1
fi

echo "JAVA_HOME=${JAVA_HOME:-unset}"
echo "ANDROID_HOME=$ANDROID_HOME"

# Live shared backend — required so the APK can sync without a post-install edit.
# Example: EXPO_PUBLIC_API_URL=https://your-host/api/v1
#          EXPO_PUBLIC_API_URL=http://192.168.1.10:8080/api/v1
API_URL="${EXPO_PUBLIC_API_URL:-${TRAILGUARD_API_URL:-}}"
if [[ -z "$API_URL" ]]; then
  echo "ERROR: Set EXPO_PUBLIC_API_URL (or TRAILGUARD_API_URL) to the live TrailGuard /api/v1 base."
  echo "  Deployed:  EXPO_PUBLIC_API_URL=https://YOUR_HOST/api/v1"
  echo "  Same Wi-Fi: EXPO_PUBLIC_API_URL=http://YOUR_LAN_IP:8080/api/v1"
  echo "Home Settings can still override the URL after install."
  exit 1
fi
export EXPO_PUBLIC_API_URL="${API_URL%/}"
echo "EXPO_PUBLIC_API_URL=$EXPO_PUBLIC_API_URL"

if [[ ! -d node_modules/expo ]]; then
  echo "Installing npm dependencies…"
  npm install --ignore-scripts
fi

echo "=== expo prebuild (android) ==="
npx expo prebuild --platform android --no-install

if [[ ! -d android ]]; then
  echo "ERROR: android/ was not generated by prebuild"
  exit 1
fi

# Patches that must survive / re-apply after every prebuild:
# 1) splash color — Expo sometimes omits splashscreen_background
# 2) embed JS in debug APK — default skips bundling and expects Metro
COLORS="android/app/src/main/res/values/colors.xml"
if [[ -f "$COLORS" ]] && ! grep -q 'splashscreen_background' "$COLORS"; then
  echo "=== patch colors.xml (splashscreen_background) ==="
  perl -0pi -e 's|</resources>|  <color name="splashscreen_background">#0A100C</color>\n</resources>|' "$COLORS"
fi
SPLASH="android/app/src/main/res/drawable/splashscreen.xml"
if [[ -f "$SPLASH" ]]; then
  perl -pi -e 's|@color/splashscreen_background|@color/colorPrimary|g' "$SPLASH" 2>/dev/null || true
  # Prefer dedicated splash color when present
  if grep -q 'splashscreen_background' "$COLORS" 2>/dev/null; then
    perl -pi -e 's|@color/colorPrimary|@color/splashscreen_background|g' "$SPLASH"
  fi
fi
APP_GRADLE="android/app/build.gradle"
if [[ -f "$APP_GRADLE" ]] && ! grep -q 'debuggableVariants = \[\]' "$APP_GRADLE"; then
  echo "=== patch build.gradle (embed JS bundle in debug) ==="
  perl -0pi -e 's|(react \{)|$1\n    // TrailGuard: ship JS inside debug APK (no Metro required on device)\n    debuggableVariants = []\n|' "$APP_GRADLE"
fi

echo "sdk.dir=$ANDROID_HOME" > android/local.properties

echo "=== gradlew assembleDebug ==="
cd android
chmod +x gradlew
./gradlew assembleDebug --no-daemon

APK_SRC="app/build/outputs/apk/debug/app-debug.apk"
if [[ ! -f "$APK_SRC" ]]; then
  echo "ERROR: expected $APK_SRC"
  find app/build/outputs -name '*.apk' 2>/dev/null || true
  exit 1
fi

OUT_DIR="$MOBILE_DIR/build/apk"
mkdir -p "$OUT_DIR"
cp "$APK_SRC" "$OUT_DIR/trailguard-debug.apk"

# Also keep a copy next to gradle output name for convenience
cp "$APK_SRC" "$OUT_DIR/app-debug.apk"

echo "DONE"
echo "APK: $OUT_DIR/trailguard-debug.apk ($(wc -c < "$OUT_DIR/trailguard-debug.apk" | tr -d ' ') bytes)"

# Quick sanity: must contain classes.dex (grep -q + pipefail → SIGPIPE 141)
if command -v unzip >/dev/null 2>&1; then
  set +o pipefail
  if ! unzip -l "$OUT_DIR/trailguard-debug.apk" | grep -Fq 'classes.dex'; then
    set -o pipefail
    echo "WARNING: APK missing classes.dex — not a runnable app"
    exit 1
  fi
  set -o pipefail
  echo "OK: classes.dex present"
fi
