#!/usr/bin/env bash
# Build an installable TrailGuard APK (DEX + native libs via Gradle).
# Requires: Android SDK, JDK 17 or 21 (not 25+).
#
# Usage:
#   EXPO_PUBLIC_API_URL=https://host/api/v1 npm run apk:debug
#   EXPO_PUBLIC_API_URL=https://host/api/v1 npm run apk:release
#
# BUILD_TYPE=debug|release (default: debug)
# Output:
#   build/apk/trailguard-debug.apk
#   build/apk/trailguard-release.apk
set -euo pipefail

MOBILE_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$MOBILE_DIR"

BUILD_TYPE="${BUILD_TYPE:-debug}"
case "$BUILD_TYPE" in
  debug|release) ;;
  *)
    echo "ERROR: BUILD_TYPE must be debug or release (got: $BUILD_TYPE)"
    exit 1
    ;;
esac

export ANDROID_SDK_ROOT="${ANDROID_SDK_ROOT:-${ANDROID_HOME:-$HOME/Library/Android/sdk}}"
export ANDROID_HOME="$ANDROID_SDK_ROOT"

# Prefer JDK 17 for React Native / Android Gradle Plugin.
if [[ -z "${JAVA_HOME:-}" ]] || ! "$JAVA_HOME/bin/java" -version 2>&1 | grep -qE '"1[7-9]\.|\"2[0-1]\.'; then
  if [[ -d "/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home" ]]; then
    export JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-17.jdk/Contents/Home"
  elif [[ -d "/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home" ]]; then
    export JAVA_HOME="/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home"
  elif [[ -d "/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home" ]]; then
    export JAVA_HOME="/Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home"
  elif command -v /usr/libexec/java_home >/dev/null 2>&1; then
    export JAVA_HOME="$(/usr/libexec/java_home -v 17 2>/dev/null || /usr/libexec/java_home -v 21 2>/dev/null || true)"
  fi
fi

if [[ -n "${JAVA_HOME:-}" ]] && "$JAVA_HOME/bin/java" -version 2>&1 | grep -qE '"2[5-9]\.|"26\.'; then
  echo "ERROR: JDK 25+ breaks the React Native Gradle plugin. Install JDK 17 or 21 (e.g. temurin-21)."
  exit 1
fi

echo "JAVA_HOME=${JAVA_HOME:-unset}"
echo "ANDROID_HOME=$ANDROID_HOME"
echo "BUILD_TYPE=$BUILD_TYPE"

# Live shared backend — required so the APK can sync without a post-install edit.
API_URL="${EXPO_PUBLIC_API_URL:-${TRAILGUARD_API_URL:-}}"
if [[ -z "$API_URL" ]]; then
  # Fall back to production park host when unset (matches app.config.js default).
  API_URL="https://trailguard-sable.vercel.app/api/v1"
fi
export EXPO_PUBLIC_API_URL="${API_URL%/}"
echo "EXPO_PUBLIC_API_URL=$EXPO_PUBLIC_API_URL"

if [[ ! -d node_modules/expo ]]; then
  echo "Installing npm dependencies…"
  npm install --ignore-scripts
fi

echo "=== expo prebuild (android) ==="
npx expo prebuild --platform android --no-install

if [[ ! -d android ]]; then
  echo "ERROR: android/ was not generated by prebuild"
  exit 1
fi

# Patches that must survive / re-apply after every prebuild:
COLORS="android/app/src/main/res/values/colors.xml"
if [[ -f "$COLORS" ]] && ! grep -q 'splashscreen_background' "$COLORS"; then
  echo "=== patch colors.xml (splashscreen_background) ==="
  perl -0pi -e 's|</resources>|  <color name="splashscreen_background">#F6F8F5</color>\n</resources>|' "$COLORS"
fi
SPLASH="android/app/src/main/res/drawable/splashscreen.xml"
if [[ -f "$SPLASH" ]]; then
  perl -pi -e 's|@color/splashscreen_background|@color/colorPrimary|g' "$SPLASH" 2>/dev/null || true
  if grep -q 'splashscreen_background' "$COLORS" 2>/dev/null; then
    perl -pi -e 's|@color/colorPrimary|@color/splashscreen_background|g' "$SPLASH"
  fi
fi
APP_GRADLE="android/app/build.gradle"
if [[ -f "$APP_GRADLE" ]] && ! grep -q 'debuggableVariants = \[\]' "$APP_GRADLE"; then
  echo "=== patch build.gradle (embed JS bundle in debug) ==="
  perl -0pi -e 's|(react \{)|$1\n    // TrailGuard: ship JS inside debug APK (no Metro required on device)\n    debuggableVariants = []\n|' "$APP_GRADLE"
fi

# Ensure cleartext allowed for LAN demo (HTTPS production still preferred).
MANIFEST="android/app/src/main/AndroidManifest.xml"
if [[ -f "$MANIFEST" ]] && ! grep -q 'usesCleartextTraffic' "$MANIFEST"; then
  echo "=== patch AndroidManifest (cleartext for LAN) ==="
  perl -pi -e 's|<application |<application android:usesCleartextTraffic="true" |' "$MANIFEST"
fi

echo "sdk.dir=$ANDROID_HOME" > android/local.properties

if [[ "$BUILD_TYPE" == "release" ]]; then
  echo "=== gradlew assembleRelease ==="
  GRADLE_TASK="assembleRelease"
  APK_SRC="app/build/outputs/apk/release/app-release.apk"
  OUT_NAME="trailguard-release.apk"
else
  echo "=== gradlew assembleDebug ==="
  GRADLE_TASK="assembleDebug"
  APK_SRC="app/build/outputs/apk/debug/app-debug.apk"
  OUT_NAME="trailguard-debug.apk"
fi

cd android
chmod +x gradlew
./gradlew "$GRADLE_TASK" --no-daemon

if [[ ! -f "$APK_SRC" ]]; then
  echo "ERROR: expected $APK_SRC"
  find app/build/outputs -name '*.apk' 2>/dev/null || true
  exit 1
fi

OUT_DIR="$MOBILE_DIR/build/apk"
mkdir -p "$OUT_DIR"
cp "$APK_SRC" "$OUT_DIR/$OUT_NAME"
cp "$APK_SRC" "$OUT_DIR/$(basename "$APK_SRC")"

echo "DONE"
echo "APK: $OUT_DIR/$OUT_NAME ($(wc -c < "$OUT_DIR/$OUT_NAME" | tr -d ' ') bytes)"
echo "Note: release is signed with the local debug keystore (installable; not Play Store upload)."

if command -v unzip >/dev/null 2>&1; then
  set +o pipefail
  if ! unzip -l "$OUT_DIR/$OUT_NAME" | grep -Fq 'classes.dex'; then
    set -o pipefail
    echo "WARNING: APK missing classes.dex — not a runnable app"
    exit 1
  fi
  set -o pipefail
  echo "OK: classes.dex present"
  if unzip -p "$OUT_DIR/$OUT_NAME" assets/index.android.bundle 2>/dev/null | grep -Fq 'trailguard-sable.vercel.app'; then
    echo "OK: live API host embedded in JS bundle"
  elif unzip -l "$OUT_DIR/$OUT_NAME" | grep -Fq 'index.android.bundle'; then
    echo "NOTE: bundle present; confirm EXPO_PUBLIC_API_URL if health fails on device"
  fi
fi
